name: Build Android APK
run-name: ${{ github.actor }} is bulding App
on: [push]
jobs:
  build:
    run-on: ubuntu-latest 
    steps:
      - name: krok1
        uses: actions/checkout@v4
        with:
          submodules: recursive
